{
 "title": "Spark Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-gps.*, '15m', 'sum')"
    }
   ]
  },
  {
   "title": "NA-vehicle diagnostics Input Rate vs Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-vin.inputRowsPerSecond"
    },
    {
     "target": "trucks.direct.progress.na-vin.processedRowsPerSecond"
    }
   ]
  },
  {
   "title": "NA-gps Total Input 30 mins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-gps.numInputRows, \"30min\", \"sum\")"
    }
   ]
  },
  {
   "title": "NA-vin Input Records vs Stored Records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-vin.numInputRows"
    },
    {
     "target": "trucks.direct.progress.na-vin.storedRecords"
    }
   ]
  },
  {
   "title": "NA-gps Input Rate vs Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-gps.inputRowsPerSecond"
    },
    {
     "target": "trucks.direct.progress.na-gps.processedRowsPerSecond"
    }
   ]
  },
  {
   "title": "NA-vin Total Input 15 mins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-vin.numInputRows, \"15min\", \"sum\")"
    }
   ]
  },
  {
   "title": "NA-gps Total Input 30 mins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-gps.numInputRows, \"30min\", \"sum\")"
    }
   ]
  },
  {
   "title": "NA-fault Input Records vs Stored Records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-fault.numInputRows"
    },
    {
     "target": "trucks.direct.progress.na-fault.storedRecords"
    }
   ]
  },
  {
   "title": "NA-gps Input Records vs Stored Records",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-gps.numInputRows"
    },
    {
     "target": "trucks.direct.progress.na-gps.storedRecords"
    }
   ]
  },
  {
   "title": "Japan - Input rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.as-jp.numInputRows"
    }
   ]
  },
  {
   "title": "NA-gps Total Input 15 mins",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-gps.numInputRows, \"15min\", \"sum\")"
    }
   ]
  },
  {
   "title": "NA Fault - Total input 15 minutes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.na-fault.numInputRows, \"15min\", \"sum\")"
    }
   ]
  },
  {
   "title": "NA Fault - Input rate vs. Processing rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.na-fault.inputRowsPerSecond"
    },
    {
     "target": "trucks.direct.progress.na-fault.processedRowsPerSecond"
    }
   ]
  },
  {
   "title": "Japan - Total Input 15 min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "summarize(trucks.direct.progress.as-jp.numInputRows, \"15min\", \"sum\")"
    }
   ]
  },
  {
   "title": "Japan - Input rate vs. Processing rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "trucks.direct.progress.as-jp.inputRowsPerSecond"
    },
    {
     "target": "trucks.direct.progress.as-jp.processedRowsPerSecond"
    }
   ]
  }
 ]
}